// Shared product data — used for seeding and as fallback

// Temporary site-wide switch: when true, every product shows as Out of
// Stock and purchasing is disabled everywhere, without editing each
// product individually. Flip back to true to pause the whole store.
export const STORE_OUT_OF_STOCK = false;

export const PRODUCTS = [
  {
    name: 'VORTEX',
    slug: 'vortex',
    in_stock: false,
    category: 'Pre-Workout Performance',
    tagline: 'Energy, focus, blood flow, and endurance — built to have you ready from the first rep to the final set.',
    description: 'A high-performance pre-workout formula supporting energy, focus, blood flow, muscular endurance, and training intensity.',
    long_description: 'VORTEX is engineered for the moments that matter most — the heavy sets, the final reps, the sessions where everything is on the line. Every ingredient is dosed to clinical standard, tested by third-party labs, and built around compounds we would take ourselves. No fillers, no proprietary blends hiding weak doses — just what works, at doses that work.',
    price: 79.99,
    serving_size: '1 scoop (10g)',
    capsule_count: '20 servings',
    made_in: 'New Zealand',
    ideal_for: 'Everyday gym-goers, fitness enthusiasts, strength athletes, and active individuals seeking greater energy, endurance, focus, and performance during training.',
    signal_path: 'M0 20 L18 20 L24 4 L30 32 L36 10 L42 26 L48 20 L120 20',
    signal_label: 'Sharp surge — pre-workout',
    cta_text: 'Ignite Your Training',
    marketing_tagline: 'Maximum intensity. Zero hesitation.',
    image_url: '/images/products/vortex.jpg',
    images: [
      '/images/products/vortex-1.jpg',
      '/images/products/vortex-2.jpg',
      '/images/products/vortex-3.jpg',
    ],
    display_order: 1,
    benefits: ['Explosive energy & focus', 'Enhanced blood flow & pumps', 'Improved muscular endurance', 'Greater training intensity'],
    ingredients: [
      { name: 'L-Citrulline', dose: '3,500mg', benefit: 'Pump, blood & flow' },
      { name: 'L-Arginine HCL', dose: '2,500mg', benefit: 'Nitric oxide support' },
      { name: 'Taurine', dose: '2,000mg', benefit: 'Hydration & endurance' },
      { name: 'Caffeine Anhydrous', dose: '200mg', benefit: 'Clean energy & focus' },
      { name: 'L-Theanine', dose: '200mg', benefit: 'Mental clarity & calm focus' },
    ],
  },
  {
    name: 'CREATINE MONOHYDRATE',
    slug: 'creatine-monohydrate',
    category: 'Strength & Performance',
    tagline: 'Pure monohydrate for strength, power, and training capacity across repeated high-intensity sessions.',
    description: 'A pure daily performance supplement supporting strength, power, training capacity, and muscular performance.',
    long_description: 'CREATINE MONOHYDRATE is the most researched, most proven supplement in performance nutrition — and we do not overcomplicate it. Pure, unflavored, micronized creatine monohydrate at clinical dose. With resistance training and proper nutrition, it supports harder training and long-term muscle development. No proprietary blend, no fillers, no labels designed to obscure — just creatine, disclosed to the milligram.',
    price: 19.99,
    serving_size: '1 scoop (5g)',
    capsule_count: '50 servings',
    made_in: 'New Zealand',
    ideal_for: 'Everyday gym-goers, bodybuilders, strength athletes, team-sport players, and active individuals building strength and power.',
    signal_path: 'M0 24 L26 24 L32 12 L38 24 L60 24 L66 12 L72 24 L120 24',
    signal_label: 'Even repeated load — strength',
    cta_text: 'Build Your Foundation',
    marketing_tagline: 'The most proven supplement. Done right.',
    image_url: '/images/products/creatine-monohydrate.jpg',
    images: [
      '/images/products/creatine-monohydrate-1.jpg',
      '/images/products/creatine-monohydrate-2.jpg',
      '/images/products/creatine-monohydrate-3.jpg',
    ],
    display_order: 2,
    benefits: ['Increased strength & power', 'Greater training capacity', 'Supports muscle development', 'Repeated high-intensity performance'],
    ingredients: [
      { name: 'Creatine Monohydrate (Micronized)', dose: '5,000mg', benefit: 'ATP production, strength & power' },
    ],
  },
  {
    name: 'SOMNUS',
    slug: 'somnus',
    category: 'Sleep & Recovery',
    tagline: 'A nighttime formula for relaxation, restful sleep, and overnight recovery — readiness for the day after.',
    description: 'A nighttime sleep and recovery formula supporting relaxation, restful sleep, sleep quality, and overnight recovery.',
    long_description: 'SOMNUS prepares body and mind for the deep, restorative sleep that every athlete, every professional, every person needs to perform. Not a sedative — a recovery formula. Calming botanicals and minerals work together to quiet the nervous system, ease the transition into sleep, and support the quality of rest that determines how you feel, train, and think the next day.',
    price: 39.99,
    serving_size: '2 capsules',
    capsule_count: '30 servings',
    made_in: 'New Zealand',
    ideal_for: 'Gym-goers, athletes, active professionals, and adults wanting better relaxation, sleep quality, and overnight recovery.',
    signal_path: 'M0 20 Q30 20 40 26 Q50 32 60 26 Q70 20 80 24 Q90 28 120 22',
    signal_label: 'Slow flattening wave — sleep',
    cta_text: 'Recover Deeper',
    marketing_tagline: 'Recovery is not rest. It is preparation.',
    image_url: '/images/products/somnus.jpg',
    images: [
      '/images/products/somnus-1.jpg',
      '/images/products/somnus-2.jpg',
      '/images/products/somnus-3.jpg',
    ],
    display_order: 3,
    benefits: ['Faster sleep onset', 'Deeper, more restful sleep', 'Overnight muscle recovery', 'Morning readiness & clarity'],
    ingredients: [
      { name: 'Valerian Root Extract', dose: '400mg', benefit: 'Relaxation & sleep onset' },
      { name: 'Passionflower Extract', dose: '300mg', benefit: 'Calming & relaxation' },
      { name: 'L-Tryptophan', dose: '300mg', benefit: 'Serotonin & melatonin support' },
    ],
  },
  {
    name: 'MAGNESIUM GLYCINATE',
    slug: 'magnesium-glycinate',
    category: 'Recovery, Relaxation & Daily Wellness',
    tagline: 'Comfortable daily magnesium for muscle function, nervous system health, relaxation, and recovery.',
    description: 'A daily mineral supplement supporting normal muscle function, nervous system health, relaxation, energy production, and recovery.',
    long_description: 'MAGNESIUM GLYCINATE is the mineral most people are missing — in the form most people can actually use. The glycinate form is chosen for its high bioavailability and gentle effect on the stomach, making it comfortable for daily use. It supports over 300 enzymatic reactions in the body, from muscle function to nervous system health to energy production. This is daily infrastructure, not a quick fix.',
    price: 24.99,
    serving_size: '4 capsules',
    capsule_count: '15 servings',
    made_in: 'New Zealand',
    ideal_for: 'Gym-goers, active adults, athletes, and busy professionals wanting muscle function, relaxation, recovery, and daily magnesium support.',
    signal_path: 'M0 22 Q20 22 30 19 Q40 16 50 20 Q60 24 70 20 Q80 16 90 20 Q100 23 120 21',
    signal_label: 'Gentle steady wave — daily calm',
    cta_text: 'Support Every Day',
    marketing_tagline: 'The mineral your body runs on.',
    image_url: '/images/products/magnesium-glycinate.jpg',
    images: [
      '/images/products/magnesium-glycinate-1.jpg',
      '/images/products/magnesium-glycinate-2.jpg',
      '/images/products/magnesium-glycinate-3.jpg',
    ],
    display_order: 4,
    benefits: ['Normal muscle function', 'Nervous system support', 'Daily relaxation & calm', 'Energy production & recovery'],
    ingredients: [
      { name: 'Magnesium Glycinate', dose: '2,400mg', benefit: 'Muscle function & relaxation' },
    ],
  },
  {
    name: 'VIGOR',
    slug: 'vigor',
    category: "Men's Vitality & Performance",
    tagline: 'Stronger Performance. Greater Confidence.',
    description: 'An advanced male performance formula designed to support healthy blood flow, sexual vitality, stamina, and confidence when it matters most.',
    long_description: 'An advanced male performance formula designed to support healthy blood flow, sexual vitality, stamina, and confidence when it matters most.',
    price: 79.99,
    serving_size: '7 capsules',
    capsule_count: '15 servings (105 capsules)',
    made_in: 'New Zealand',
    ideal_for: 'Men wanting more from energy, stamina, circulation, confidence, and everyday performance.',
    signal_path: 'M0 22 L16 22 L22 6 L28 34 L34 6 L40 22 L64 22 L70 6 L76 34 L82 6 L88 22 L120 22',
    signal_label: 'Double peak — vitality & drive',
    cta_text: 'Unlock Your Vigor',
    marketing_tagline: 'BETTER BLOOD FLOW. STRONGER MALE PERFORMANCE.',
    marketing_statement: 'Supports healthy circulation, normal erectile function, firmness, fullness, stamina, vitality, and confidence—for stronger male performance when it matters most.',
    image_url: '/images/products/vigor.jpg',
    images: [
      '/images/products/vigor-1.jpg',
      '/images/products/vigor-2.jpg',
      '/images/products/vigor-3.jpg',
    ],
    display_order: 5,
    benefits: [
      { title: 'Supports Sexual Desire', description: 'Helps promote healthy libido, vitality, and physical readiness.' },
      { title: 'Promotes Healthy Blood Flow', description: 'Supports nitric oxide production and healthy circulation for improved blood delivery throughout the body.' },
      { title: 'Supports Firmer, Fuller Erections', description: 'Helps support normal erectile function, firmness, and fullness during intimacy.' },
      { title: 'Helps Maintain Performance', description: 'Supports sustained firmness and consistent performance for longer-lasting confidence.' },
      { title: 'Enhances Sexual Stamina', description: 'Helps reduce fatigue and supports endurance, energy, and staying power.' },
      { title: 'Supports Sexual Response', description: 'Helps promote physical responsiveness and greater confidence during intimate moments.' },
      { title: 'Boosts Energy and Vitality', description: 'Supports physical and mental energy for both sexual performance and everyday life.' },
      { title: 'Promotes Confidence Under Pressure', description: 'Helps you feel more prepared, capable, and confident when performance matters.' },
    ],
    ingredients: [
      { name: 'L-Citrulline', dose: '1,800mg', benefit: 'Circulation & performance' },
      { name: 'Epimedium Extract', dose: '1,270mg', benefit: 'Vitality & confidence' },
      { name: 'Panax Ginseng Extract', dose: '600mg', benefit: 'Stamina & alertness' },
      { name: 'Beetroot Extract', dose: '300mg', benefit: 'Nitric oxide & circulation' },
      { name: 'Zinc Acetate', dose: '10mg', benefit: 'Testosterone & immune support' },
      { name: 'Black Pepper Extract', dose: '6mg', benefit: 'Absorption' },
    ],
  },
  {
    name: 'THE STACK',
    slug: 'the-stack',
    category: 'Complete System',
    tagline: 'All five Viitalon formulas in one — energy, strength, recovery, calm, and vitality. The complete system, engineered to work together.',
    description: 'A complete supplement system combining VORTEX, CREATINE MONOHYDRATE, SOMNUS, MAGNESIUM GLYCINATE, and VIGOR — five fully disclosed formulas covering every pillar of performance.',
    long_description: 'THE STACK is the complete Viitalon system. Five formulas, each engineered to clinical standard, each fully disclosed to the milligram. Together they cover every pillar of physical performance: energy and focus for training, strength and power output, deep overnight recovery, daily mineral support, and male vitality. This is not a random assortment — it is a coordinated system designed to work in concert. Train hard with VORTEX. Build with CREATINE. Recover with SOMNUS. Support daily with MAGNESIUM. Optimize with VIGOR. One stack. Every signal covered.',
    price: 179.99,
    serving_size: 'See individual formulas',
    capsule_count: 'All five formulas included',
    made_in: 'New Zealand',
    ideal_for: 'Anyone committed to complete self-optimization — covering training, strength, recovery, daily wellness, and vitality in one coordinated system.',
    signal_path: 'M0 22 L16 22 L22 6 L28 22 L40 22 L46 12 L52 22 L64 22 L70 6 L76 22 L88 22 L94 12 L100 22 L120 22',
    signal_label: 'Five signals — complete system',
    cta_text: 'Take the Full Stack',
    marketing_tagline: 'Five signals. One system. Complete.',
    image_url: '/images/products/the-stack.jpg',
    images: [
      '/images/products/the-stack-1.jpg',
      '/images/products/the-stack-2.jpg',
      '/images/products/the-stack-3.jpg',
    ],
    display_order: 6,
    benefits: ['Complete performance coverage', 'Energy, strength & power', 'Deep recovery & sleep', 'Daily wellness & vitality', 'Save vs. individual formulas'],
    ingredients: [
      { name: 'VORTEX — Pre-Workout', dose: '20 servings', benefit: 'Energy, focus & blood flow' },
      { name: 'CREATINE MONOHYDRATE', dose: '50 servings', benefit: 'Strength & power' },
      { name: 'SOMNUS — Sleep & Recovery', dose: '30 servings', benefit: 'Deep sleep & overnight recovery' },
      { name: 'MAGNESIUM GLYCINATE', dose: '15 servings', benefit: 'Muscle function & calm' },
      { name: 'VIGOR — Men\'s Vitality', dose: '15 servings', benefit: 'Vitality & performance' },
    ],
  },
  {
    name: 'REDLINE STACK',
    slug: 'redline-stack',
    category: "Men's Performance System",
    tagline: 'TESTCORE + FLOWCORE — a total men\'s performance system for training, energy, circulation and everyday vitality.',
    description: 'REDLINE STACK combines TESTCORE and FLOWCORE into a complete daily men\'s performance system designed to support vitality, energy, healthy circulation, endurance and physical performance.',
    long_description: 'REDLINE STACK combines TESTCORE and FLOWCORE into a complete daily men\'s performance system designed to support vitality, energy, healthy circulation, endurance and physical performance. Rather than focusing on one area alone, REDLINE is designed to support performance in training, throughout the day and in everyday life — power your training, drive your day, elevate your performance. This is daily performance, not just pre-workout: use TESTCORE and FLOWCORE every day, including rest days, according to the serving directions on each label, at approximately the same time each day for best consistency. For users who tolerate the products well, the morning serving may be taken before breakfast or between meals; if stomach sensitivity occurs, take with food. Do not exceed the recommended daily serving. Train harder. Live stronger. Perform every day.',
    price: 299.00,
    serving_size: 'Per label — TESTCORE & FLOWCORE',
    capsule_count: '6 bottles · 90-day supply (3× TESTCORE, 3× FLOWCORE)',
    made_in: 'New Zealand',
    ideal_for: 'Men wanting a complete daily performance system covering vitality, energy, circulation, endurance and training performance — used consistently as a 90-day program.',
    signal_path: '',
    signal_label: 'Two systems, one daily stack',
    cta_text: 'Get the Redline Stack',
    marketing_tagline: 'POWER YOUR TRAINING. DRIVE YOUR DAY. ELEVATE YOUR PERFORMANCE.',
    marketing_statement: 'TESTCORE and FLOWCORE combine into one complete daily performance system — designed for training, throughout the day, and everyday life.',
    image_url: '/images/products/redline-stack.jpg',
    images: [
      '/images/products/redline-stack.jpg',
    ],
    display_order: 7,
    benefits: [
      { title: 'Daily Energy & Drive', description: 'Supports consistent energy, motivation and everyday vitality.' },
      { title: 'Blood Flow & Circulation', description: 'Supports healthy circulation and efficient blood flow throughout the body.' },
      { title: 'Pumps & Training Performance', description: 'Supports nitric oxide production, muscle pumps and physical performance.' },
      { title: 'Endurance', description: 'Supports stamina and the ability to maintain performance during demanding activity.' },
      { title: 'Male Vitality', description: 'Designed to support overall male vitality, drive and confidence.' },
      { title: 'Cardiovascular Support*', description: 'Supports normal cardiovascular and circulatory function.' },
      { title: 'Liver & Kidney Function*', description: 'Supports normal healthy liver and kidney function as part of overall wellness.' },
    ],
    ingredients: [
      { name: 'TESTCORE — Test Support', dose: '3 bottles · 60 capsules each', benefit: 'Male vitality, drive & hormone function' },
      { name: 'FLOWCORE — Blood Flow Support', dose: '3 bottles · 60 capsules each', benefit: 'Circulation, pumps & endurance' },
    ],
  },
];

export const HERO_IMAGE = 'https://media.base44.com/images/public/6a612aebbf4c407efb5ed4ff/b666fb064_web1.png';
export const BRAND_STORY_IMAGE = 'https://media.base44.com/images/public/6a612aebbf4c407efb5ed4ff/0c9b39226_generated_4f8dc19e.png';
export const LOGO_URL = 'https://media.base44.com/images/public/6a612aebbf4c407efb5ed4ff/8be985cd3_viitalon_logo-removebg-preview.png';
